# Data Pre-processing
## Steps:
1. **Getting Datasets**
2. **Import Libraries**
3. **Import Datasets**
4. **Find Missing Values**
5. **Encoding categorical dataset**
6. **Splitting data into training and testing dataset**
7. **Feature Scaling**

In [1]:
import pandas as pd
import numpy as np 

In [2]:
dataset=pd.read_csv("Data.csv")
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  83000.0       Yes
8  Germany  50.0  67000.0        No

In [3]:
#x+y=z

x=dataset[['Country','Age','Salary']].values #These are independent variable
y=dataset[['Purchased']]

x


array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 83000.0],
       ['Germany', 50.0, 67000.0]], dtype=object)

## Find Missing Values:

In [4]:
from sklearn.impute import SimpleImputer

imputer=SimpleImputer(missing_values=np.nan, strategy='median') #default is mean
imputer=imputer.fit(x[:,1:3])
x[:,1:3]=imputer.transform(x[:,1:3])
x


array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 59500.0],
       ['France', 35.0, 58000.0],
       ['Spain', 39.0, 52000.0],
       ['France', 48.0, 83000.0],
       ['Germany', 50.0, 67000.0]], dtype=object)

## Encoding Categorical Data:
The country column will be encoded

In [6]:
from sklearn.preprocessing import LabelEncoder

label_encoder_x=LabelEncoder()
x[:,0]=label_encoder_x.fit_transform(x[:,0])
x

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 59500.0],
       [0, 35.0, 58000.0],
       [2, 39.0, 52000.0],
       [0, 48.0, 83000.0],
       [1, 50.0, 67000.0]], dtype=object)

## Training & Testing Dataset:

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=0)
x_train,x_test,y_train,y_test


(array([[2, 27.0, 48000.0],
        [1, 40.0, 59500.0],
        [1, 50.0, 67000.0],
        [2, 39.0, 52000.0],
        [2, 38.0, 61000.0],
        [0, 44.0, 72000.0],
        [0, 35.0, 58000.0]], dtype=object),
 array([[0, 48.0, 83000.0],
        [1, 30.0, 54000.0]], dtype=object),
   Purchased
 1       Yes
 4       Yes
 8        No
 6        No
 3        No
 0        No
 5       Yes,
   Purchased
 7       Yes
 2        No)

# Feature Scaling:

In [9]:
from sklearn.preprocessing import StandardScaler

In [11]:
sc_x=StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.fit_transform(x_test)
x_test
x_train

array([[ 1.02899151, -1.80906807, -1.52999381],
       [-0.17149859,  0.15075567, -0.01877293],
       [-0.17149859,  1.6583124 ,  0.9668059 ],
       [ 1.02899151,  0.        , -1.00435176],
       [ 1.02899151, -0.15075567,  0.17834284],
       [-1.37198868,  0.75377836,  1.62385846],
       [-1.37198868, -0.60302269, -0.2158887 ]])